# TCL File Generated by Component Editor 21.4
# Wed Apr 13 16:46:20 IST 2022
# DO NOT MODIFY


#
# start_tod_sync "Etile tod subsystem start_tod_sync set IP" v1.0.0
# Intel Corporation 2022.04.13.16:46:20
#
#****************************************************************************
#

#
# request TCL package from ACDS 21.4
#
package require -exact qsys 21.4


#
# module start_tod_sync
#
set_module_property DESCRIPTION ""
set_module_property NAME start_tod_sync
set_module_property VERSION 1.0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Example Designs/Ethernet/Misc"
set_module_property AUTHOR "Intel Corporation"
set_module_property DISPLAY_NAME "Etile tod subsystem start_tod_sync set IP"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK true
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0

#
# file sets
#
add_fileset synthesis_fileset QUARTUS_SYNTH "" ""
set_fileset_property synthesis_fileset TOP_LEVEL start_tod_sync
set_fileset_property synthesis_fileset ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property synthesis_fileset ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file start_tod_sync.v VERILOG PATH start_tod_sync.v TOP_LEVEL_FILE

add_fileset sim_verilog_fileset SIM_VERILOG "" ""
set_fileset_property sim_verilog_fileset TOP_LEVEL start_tod_sync
set_fileset_property sim_verilog_fileset ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property sim_verilog_fileset ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file start_tod_sync.v VERILOG PATH start_tod_sync.v TOP_LEVEL_FILE

add_fileset sim_vhdl_fileset SIM_VHDL "" ""
set_fileset_property sim_vhdl_fileset TOP_LEVEL start_tod_sync
set_fileset_property sim_vhdl_fileset ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property sim_vhdl_fileset ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file start_tod_sync.v VERILOG PATH start_tod_sync.v TOP_LEVEL_FILE


#
# TX 25Gbe TOD start_tod_sync
#
add_interface tx_tod_25gbe_start_tod_sync conduit end
set_interface_property tx_tod_25gbe_start_tod_sync associatedClock ""
set_interface_property tx_tod_25gbe_start_tod_sync associatedReset ""
set_interface_property tx_tod_25gbe_start_tod_sync ENABLED true
set_interface_property tx_tod_25gbe_start_tod_sync EXPORT_OF ""
set_interface_property tx_tod_25gbe_start_tod_sync PORT_NAME_MAP ""
set_interface_property tx_tod_25gbe_start_tod_sync CMSIS_SVD_VARIABLES ""
set_interface_property tx_tod_25gbe_start_tod_sync SVD_ADDRESS_GROUP ""
set_interface_property tx_tod_25gbe_start_tod_sync IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_tod_25gbe_start_tod_sync tx_tod_25gbe_start_tod_sync data Output 1

#
# RX 25Gbe TOD start_tod_sync
#
add_interface rx_tod_25gbe_start_tod_sync conduit end
set_interface_property rx_tod_25gbe_start_tod_sync associatedClock ""
set_interface_property rx_tod_25gbe_start_tod_sync associatedReset ""
set_interface_property rx_tod_25gbe_start_tod_sync ENABLED true
set_interface_property rx_tod_25gbe_start_tod_sync EXPORT_OF ""
set_interface_property rx_tod_25gbe_start_tod_sync PORT_NAME_MAP ""
set_interface_property rx_tod_25gbe_start_tod_sync CMSIS_SVD_VARIABLES ""
set_interface_property rx_tod_25gbe_start_tod_sync SVD_ADDRESS_GROUP ""
set_interface_property rx_tod_25gbe_start_tod_sync IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_tod_25gbe_start_tod_sync rx_tod_25gbe_start_tod_sync data Output 1

#
# TX 10Gbe TOD start_tod_sync
#
add_interface tx_tod_10gbe_start_tod_sync conduit end
set_interface_property tx_tod_10gbe_start_tod_sync associatedClock ""
set_interface_property tx_tod_10gbe_start_tod_sync associatedReset ""
set_interface_property tx_tod_10gbe_start_tod_sync ENABLED true
set_interface_property tx_tod_10gbe_start_tod_sync EXPORT_OF ""
set_interface_property tx_tod_10gbe_start_tod_sync PORT_NAME_MAP ""
set_interface_property tx_tod_10gbe_start_tod_sync CMSIS_SVD_VARIABLES ""
set_interface_property tx_tod_10gbe_start_tod_sync SVD_ADDRESS_GROUP ""
set_interface_property tx_tod_10gbe_start_tod_sync IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_tod_10gbe_start_tod_sync tx_tod_10gbe_start_tod_sync data Output 1

#
# RX 10Gbe TOD start_tod_sync
#
add_interface rx_tod_10gbe_start_tod_sync conduit end
set_interface_property rx_tod_10gbe_start_tod_sync associatedClock ""
set_interface_property rx_tod_10gbe_start_tod_sync associatedReset ""
set_interface_property rx_tod_10gbe_start_tod_sync ENABLED true
set_interface_property rx_tod_10gbe_start_tod_sync EXPORT_OF ""
set_interface_property rx_tod_10gbe_start_tod_sync PORT_NAME_MAP ""
set_interface_property rx_tod_10gbe_start_tod_sync CMSIS_SVD_VARIABLES ""
set_interface_property rx_tod_10gbe_start_tod_sync SVD_ADDRESS_GROUP ""
set_interface_property rx_tod_10gbe_start_tod_sync IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_tod_10gbe_start_tod_sync rx_tod_10gbe_start_tod_sync data Output 1
