################################################
#
# SPDX-License-Identifier: MIT-0
# Copyright(c) 2021-2021 Intel Corporation.
#
################################################
#
# Make include file for Board "PCIE Devkit"
# This file define the supported configuration
#
################################################

#SM
DEVICE ?= A5ED065BB32AE5SR0

#HPS EMIF Reference Clock
HPS_EMIF_REF_CLK_FREQ_MHZ ?= "33.333"
