#****************************************************************************
#
# SPDX-License-Identifier: MIT-0
# Copyright(c) 2001-2020 Intel Corporation.
#
#****************************************************************************
#
# TCL File Generated by Component Editor 16.1
# DO NOT MODIFY
#
# eth_tod_load_off "eth_tod_load_off" v1.0
#
# request TCL package from ACDS 16.1
#****************************************************************************

package require -exact qsys 16.1


#
# module eth_tod_load_off
#
set_module_property DESCRIPTION ""
set_module_property NAME eth_tod_load_off
set_module_property VERSION 1.0.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Intel Corporation"
set_module_property GROUP "Example Designs/Ethernet/Misc"
set_module_property DISPLAY_NAME "Terminate TOD Load input with 0"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL eth_tod_load_off
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file eth_tod_load_off.v VERILOG PATH eth_tod_load_off.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL eth_tod_load_off
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file eth_tod_load_off.v VERILOG PATH eth_tod_load_off.v


#
# parameters
#
add_parameter CONDUIT_DATA_WIDTH INTEGER 96 ""
set_parameter_property CONDUIT_DATA_WIDTH DEFAULT_VALUE 96
set_parameter_property CONDUIT_DATA_WIDTH DISPLAY_NAME time_of_day_load
set_parameter_property CONDUIT_DATA_WIDTH TYPE INTEGER
set_parameter_property CONDUIT_DATA_WIDTH UNITS None
set_parameter_property CONDUIT_DATA_WIDTH ALLOWED_RANGES {"64" "96"}
set_parameter_property CONDUIT_DATA_WIDTH DESCRIPTION ""
set_parameter_property CONDUIT_DATA_WIDTH HDL_PARAMETER true


#
# display items
#


#
# connection point time_of_day_load
#
add_interface time_of_day_load avalon_streaming source
set_interface_property time_of_day_load associatedClock ""
set_interface_property time_of_day_load associatedReset ""
set_interface_property time_of_day_load ENABLED true
set_interface_property time_of_day_load EXPORT_OF ""
set_interface_property time_of_day_load PORT_NAME_MAP ""
set_interface_property time_of_day_load CMSIS_SVD_VARIABLES ""
set_interface_property time_of_day_load SVD_ADDRESS_GROUP ""

add_interface_port time_of_day_load time_of_day_load_data data Output CONDUIT_DATA_WIDTH
add_interface_port time_of_day_load time_of_day_load_valid valid Output 1

