# TCL File Generated by Component Editor 21.4
# Fri May 27 13:54:20 IST 2022
# DO NOT MODIFY

#
# tod_mux "ToD mux for ETILE 10G / 25G" v1.0.0
# sel =0 -> tx_tod10g & rx_tod10g; sel =1 -> tx_tod25g & rx_tod25g
# Intel Corporation 2022.05.27.13:54:20
#

#
# request TCL package from ACDS 21.4
#
package require -exact qsys 21.4

#
# module tod_mux
#
set_module_property DESCRIPTION ""
set_module_property NAME tod_mux
set_module_property VERSION 1.0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Example Designs/Ethernet/Misc"
set_module_property AUTHOR "Intel Corporation"
set_module_property DISPLAY_NAME "ToD MUX for ETILE 10G / 25G"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK true
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0

#
# file sets
#
add_fileset synthesis_fileset QUARTUS_SYNTH "" ""
set_fileset_property synthesis_fileset TOP_LEVEL tod_mux
set_fileset_property synthesis_fileset ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property synthesis_fileset ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file tod_mux.v VERILOG PATH tod_mux.v TOP_LEVEL_FILE

add_fileset sim_verilog_fileset SIM_VERILOG "" ""
set_fileset_property sim_verilog_fileset TOP_LEVEL tod_mux
set_fileset_property sim_verilog_fileset ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property sim_verilog_fileset ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file tod_mux.v VERILOG PATH tod_mux.v TOP_LEVEL_FILE

add_fileset sim_vhdl_fileset SIM_VHDL "" ""
set_fileset_property sim_vhdl_fileset TOP_LEVEL tod_mux
set_fileset_property sim_vhdl_fileset ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property sim_vhdl_fileset ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file tod_mux.v VERILOG PATH tod_mux.v TOP_LEVEL_FILE

#
# tod_sync_data tod_mux
#
add_interface tx_tod_out avalon_streaming source
set_interface_property tx_tod_out associatedClock ""
set_interface_property tx_tod_out associatedReset ""
set_interface_property tx_tod_out ENABLED true
set_interface_property tx_tod_out EXPORT_OF ""
set_interface_property tx_tod_out PORT_NAME_MAP ""
set_interface_property tx_tod_out CMSIS_SVD_VARIABLES ""
set_interface_property tx_tod_out SVD_ADDRESS_GROUP ""
set_interface_property tx_tod_out IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_tod_out tx_tod_out data Output 96

#
# tod_sync_data tod_mux
#
add_interface rx_tod_out avalon_streaming source
set_interface_property rx_tod_out associatedClock ""
set_interface_property rx_tod_out associatedReset ""
set_interface_property rx_tod_out ENABLED true
set_interface_property rx_tod_out EXPORT_OF ""
set_interface_property rx_tod_out PORT_NAME_MAP ""
set_interface_property rx_tod_out CMSIS_SVD_VARIABLES ""
set_interface_property rx_tod_out SVD_ADDRESS_GROUP ""
set_interface_property rx_tod_out IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_tod_out rx_tod_out data Output 96
#
# tod_sync_25G_data tod_mux
#
add_interface tx_tod10g avalon_streaming sink
set_interface_property tx_tod10g associatedClock ""
set_interface_property tx_tod10g associatedReset ""
set_interface_property tx_tod10g ENABLED true
set_interface_property tx_tod10g EXPORT_OF ""
set_interface_property tx_tod10g PORT_NAME_MAP ""
set_interface_property tx_tod10g CMSIS_SVD_VARIABLES ""
set_interface_property tx_tod10g SVD_ADDRESS_GROUP ""
set_interface_property tx_tod10g IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_tod10g tx_tod10g data Input 96

#
# tod_sync_10G_data tod_mux
#
add_interface tx_tod25g avalon_streaming sink
set_interface_property tx_tod25g associatedClock ""
set_interface_property tx_tod25g associatedReset ""
set_interface_property tx_tod25g ENABLED true
set_interface_property tx_tod25g EXPORT_OF ""
set_interface_property tx_tod25g PORT_NAME_MAP ""
set_interface_property tx_tod25g CMSIS_SVD_VARIABLES ""
set_interface_property tx_tod25g SVD_ADDRESS_GROUP ""
set_interface_property tx_tod25g IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_tod25g tx_tod25g data Input 96

#
# tod_sync_10G_data tod_mux
#
add_interface rx_tod10g avalon_streaming sink
set_interface_property rx_tod10g associatedClock ""
set_interface_property rx_tod10g associatedReset ""
set_interface_property rx_tod10g ENABLED true
set_interface_property rx_tod10g EXPORT_OF ""
set_interface_property rx_tod10g PORT_NAME_MAP ""
set_interface_property rx_tod10g CMSIS_SVD_VARIABLES ""
set_interface_property rx_tod10g SVD_ADDRESS_GROUP ""
set_interface_property rx_tod10g IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_tod10g rx_tod10g data Input 96

#
# tod_sync_10G_data tod_mux
#
add_interface rx_tod25g avalon_streaming sink
set_interface_property rx_tod25g associatedClock ""
set_interface_property rx_tod25g associatedReset ""
set_interface_property rx_tod25g ENABLED true
set_interface_property rx_tod25g EXPORT_OF ""
set_interface_property rx_tod25g PORT_NAME_MAP ""
set_interface_property rx_tod25g CMSIS_SVD_VARIABLES ""
set_interface_property rx_tod25g SVD_ADDRESS_GROUP ""
set_interface_property rx_tod25g IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_tod25g rx_tod25g data Input 96
#
# en_25g_10G tod_mux
#
add_interface sel conduit end
set_interface_property sel associatedClock ""
set_interface_property sel associatedReset ""
set_interface_property sel ENABLED true
set_interface_property sel EXPORT_OF ""
set_interface_property sel PORT_NAME_MAP ""
set_interface_property sel CMSIS_SVD_VARIABLES ""
set_interface_property sel SVD_ADDRESS_GROUP ""
set_interface_property sel IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port sel sel export Input 1

